# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: c_m_update_topology.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='c_m_update_topology.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x19\x63_m_update_topology.proto\"\x87\x01\n\x13\x63_m_update_topology\x12\x14\n\x07\x63ommand\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x17\n\nnode1_name\x18\x02 \x01(\tH\x01\x88\x01\x01\x12\x17\n\nnode2_name\x18\x03 \x01(\tH\x02\x88\x01\x01\x42\n\n\x08_commandB\r\n\x0b_node1_nameB\r\n\x0b_node2_nameb\x06proto3'
)




_C_M_UPDATE_TOPOLOGY = _descriptor.Descriptor(
  name='c_m_update_topology',
  full_name='c_m_update_topology',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='command', full_name='c_m_update_topology.command', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='node1_name', full_name='c_m_update_topology.node1_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='node2_name', full_name='c_m_update_topology.node2_name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_command', full_name='c_m_update_topology._command',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_node1_name', full_name='c_m_update_topology._node1_name',
      index=1, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_node2_name', full_name='c_m_update_topology._node2_name',
      index=2, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=30,
  serialized_end=165,
)

_C_M_UPDATE_TOPOLOGY.oneofs_by_name['_command'].fields.append(
  _C_M_UPDATE_TOPOLOGY.fields_by_name['command'])
_C_M_UPDATE_TOPOLOGY.fields_by_name['command'].containing_oneof = _C_M_UPDATE_TOPOLOGY.oneofs_by_name['_command']
_C_M_UPDATE_TOPOLOGY.oneofs_by_name['_node1_name'].fields.append(
  _C_M_UPDATE_TOPOLOGY.fields_by_name['node1_name'])
_C_M_UPDATE_TOPOLOGY.fields_by_name['node1_name'].containing_oneof = _C_M_UPDATE_TOPOLOGY.oneofs_by_name['_node1_name']
_C_M_UPDATE_TOPOLOGY.oneofs_by_name['_node2_name'].fields.append(
  _C_M_UPDATE_TOPOLOGY.fields_by_name['node2_name'])
_C_M_UPDATE_TOPOLOGY.fields_by_name['node2_name'].containing_oneof = _C_M_UPDATE_TOPOLOGY.oneofs_by_name['_node2_name']
DESCRIPTOR.message_types_by_name['c_m_update_topology'] = _C_M_UPDATE_TOPOLOGY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

c_m_update_topology = _reflection.GeneratedProtocolMessageType('c_m_update_topology', (_message.Message,), {
  'DESCRIPTOR' : _C_M_UPDATE_TOPOLOGY,
  '__module__' : 'c_m_update_topology_pb2'
  # @@protoc_insertion_point(class_scope:c_m_update_topology)
  })
_sym_db.RegisterMessage(c_m_update_topology)


# @@protoc_insertion_point(module_scope)
