# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: control_mgs.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='control_mgs.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x11\x63ontrol_mgs.proto\"\x97\x01\n\x0b\x63ontrol_msg\x12\x15\n\x08\x63md_name\x18\x01 \x01(\x05H\x00\x88\x01\x01\x12\x19\n\x0c\x63md_receiver\x18\x02 \x01(\tH\x01\x88\x01\x01\x12\x10\n\x03\x63md\x18\x03 \x01(\tH\x02\x88\x01\x01\x12\x1e\n\tcmd_param\x18\x04 \x03(\x0b\x32\x0b.ParametersB\x0b\n\t_cmd_nameB\x0f\n\r_cmd_receiverB\x06\n\x04_cmd\"\xec\x01\n\nParameters\x12\x11\n\x04\x61rg1\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x11\n\x04\x61rg2\x18\x02 \x01(\tH\x01\x88\x01\x01\x12\x11\n\x04\x61rg3\x18\x03 \x01(\tH\x02\x88\x01\x01\x12\x11\n\x04\x61rg4\x18\x04 \x01(\tH\x03\x88\x01\x01\x12\x11\n\x04\x61rg5\x18\x05 \x01(\tH\x04\x88\x01\x01\x12\x11\n\x04\x61rg6\x18\x06 \x01(\tH\x05\x88\x01\x01\x12\x11\n\x04\x61rg7\x18\x07 \x01(\tH\x06\x88\x01\x01\x12\x11\n\x04\x61rg8\x18\x08 \x01(\tH\x07\x88\x01\x01\x42\x07\n\x05_arg1B\x07\n\x05_arg2B\x07\n\x05_arg3B\x07\n\x05_arg4B\x07\n\x05_arg5B\x07\n\x05_arg6B\x07\n\x05_arg7B\x07\n\x05_arg8b\x06proto3'
)




_CONTROL_MSG = _descriptor.Descriptor(
  name='control_msg',
  full_name='control_msg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='cmd_name', full_name='control_msg.cmd_name', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='cmd_receiver', full_name='control_msg.cmd_receiver', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='cmd', full_name='control_msg.cmd', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='cmd_param', full_name='control_msg.cmd_param', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_cmd_name', full_name='control_msg._cmd_name',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_cmd_receiver', full_name='control_msg._cmd_receiver',
      index=1, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_cmd', full_name='control_msg._cmd',
      index=2, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=22,
  serialized_end=173,
)


_PARAMETERS = _descriptor.Descriptor(
  name='Parameters',
  full_name='Parameters',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='arg1', full_name='Parameters.arg1', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='arg2', full_name='Parameters.arg2', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='arg3', full_name='Parameters.arg3', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='arg4', full_name='Parameters.arg4', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='arg5', full_name='Parameters.arg5', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='arg6', full_name='Parameters.arg6', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='arg7', full_name='Parameters.arg7', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='arg8', full_name='Parameters.arg8', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_arg1', full_name='Parameters._arg1',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_arg2', full_name='Parameters._arg2',
      index=1, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_arg3', full_name='Parameters._arg3',
      index=2, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_arg4', full_name='Parameters._arg4',
      index=3, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_arg5', full_name='Parameters._arg5',
      index=4, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_arg6', full_name='Parameters._arg6',
      index=5, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_arg7', full_name='Parameters._arg7',
      index=6, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_arg8', full_name='Parameters._arg8',
      index=7, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=176,
  serialized_end=412,
)

_CONTROL_MSG.fields_by_name['cmd_param'].message_type = _PARAMETERS
_CONTROL_MSG.oneofs_by_name['_cmd_name'].fields.append(
  _CONTROL_MSG.fields_by_name['cmd_name'])
_CONTROL_MSG.fields_by_name['cmd_name'].containing_oneof = _CONTROL_MSG.oneofs_by_name['_cmd_name']
_CONTROL_MSG.oneofs_by_name['_cmd_receiver'].fields.append(
  _CONTROL_MSG.fields_by_name['cmd_receiver'])
_CONTROL_MSG.fields_by_name['cmd_receiver'].containing_oneof = _CONTROL_MSG.oneofs_by_name['_cmd_receiver']
_CONTROL_MSG.oneofs_by_name['_cmd'].fields.append(
  _CONTROL_MSG.fields_by_name['cmd'])
_CONTROL_MSG.fields_by_name['cmd'].containing_oneof = _CONTROL_MSG.oneofs_by_name['_cmd']
_PARAMETERS.oneofs_by_name['_arg1'].fields.append(
  _PARAMETERS.fields_by_name['arg1'])
_PARAMETERS.fields_by_name['arg1'].containing_oneof = _PARAMETERS.oneofs_by_name['_arg1']
_PARAMETERS.oneofs_by_name['_arg2'].fields.append(
  _PARAMETERS.fields_by_name['arg2'])
_PARAMETERS.fields_by_name['arg2'].containing_oneof = _PARAMETERS.oneofs_by_name['_arg2']
_PARAMETERS.oneofs_by_name['_arg3'].fields.append(
  _PARAMETERS.fields_by_name['arg3'])
_PARAMETERS.fields_by_name['arg3'].containing_oneof = _PARAMETERS.oneofs_by_name['_arg3']
_PARAMETERS.oneofs_by_name['_arg4'].fields.append(
  _PARAMETERS.fields_by_name['arg4'])
_PARAMETERS.fields_by_name['arg4'].containing_oneof = _PARAMETERS.oneofs_by_name['_arg4']
_PARAMETERS.oneofs_by_name['_arg5'].fields.append(
  _PARAMETERS.fields_by_name['arg5'])
_PARAMETERS.fields_by_name['arg5'].containing_oneof = _PARAMETERS.oneofs_by_name['_arg5']
_PARAMETERS.oneofs_by_name['_arg6'].fields.append(
  _PARAMETERS.fields_by_name['arg6'])
_PARAMETERS.fields_by_name['arg6'].containing_oneof = _PARAMETERS.oneofs_by_name['_arg6']
_PARAMETERS.oneofs_by_name['_arg7'].fields.append(
  _PARAMETERS.fields_by_name['arg7'])
_PARAMETERS.fields_by_name['arg7'].containing_oneof = _PARAMETERS.oneofs_by_name['_arg7']
_PARAMETERS.oneofs_by_name['_arg8'].fields.append(
  _PARAMETERS.fields_by_name['arg8'])
_PARAMETERS.fields_by_name['arg8'].containing_oneof = _PARAMETERS.oneofs_by_name['_arg8']
DESCRIPTOR.message_types_by_name['control_msg'] = _CONTROL_MSG
DESCRIPTOR.message_types_by_name['Parameters'] = _PARAMETERS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

control_msg = _reflection.GeneratedProtocolMessageType('control_msg', (_message.Message,), {
  'DESCRIPTOR' : _CONTROL_MSG,
  '__module__' : 'control_mgs_pb2'
  # @@protoc_insertion_point(class_scope:control_msg)
  })
_sym_db.RegisterMessage(control_msg)

Parameters = _reflection.GeneratedProtocolMessageType('Parameters', (_message.Message,), {
  'DESCRIPTOR' : _PARAMETERS,
  '__module__' : 'control_mgs_pb2'
  # @@protoc_insertion_point(class_scope:Parameters)
  })
_sym_db.RegisterMessage(Parameters)


# @@protoc_insertion_point(module_scope)
