# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: p2p_messaging.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13p2p_messaging.proto\"\x1e\n\x0bPeerRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1c\n\tPeerReply\x12\x0f\n\x07message\x18\x01 \x01(\t27\n\nP2PService\x12)\n\x0bPeerMessage\x12\x0c.PeerRequest\x1a\n.PeerReply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'p2p_messaging_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_PEERREQUEST']._serialized_start=23
  _globals['_PEERREQUEST']._serialized_end=53
  _globals['_PEERREPLY']._serialized_start=55
  _globals['_PEERREPLY']._serialized_end=83
  _globals['_P2PSERVICE']._serialized_start=85
  _globals['_P2PSERVICE']._serialized_end=140
# @@protoc_insertion_point(module_scope)
