# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from lib import p2p_messaging_pb2 as p2p__messaging__pb2


class P2PServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PeerMessage = channel.unary_unary(
                '/P2PService/PeerMessage',
                request_serializer=p2p__messaging__pb2.PeerRequest.SerializeToString,
                response_deserializer=p2p__messaging__pb2.PeerReply.FromString,
                )


class P2PServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def PeerMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_P2PServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PeerMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.PeerMessage,
                    request_deserializer=p2p__messaging__pb2.PeerRequest.FromString,
                    response_serializer=p2p__messaging__pb2.PeerReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'P2PService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class P2PService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def PeerMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/P2PService/PeerMessage',
            p2p__messaging__pb2.PeerRequest.SerializeToString,
            p2p__messaging__pb2.PeerReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
